import type { PropSidebarItemLink, SidebarsConfig } from "@docusaurus/plugin-content-docs";
import { pythonSidebarItems } from './python';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const languagesLink: PropSidebarItemLink = {
  type: "link",
  href: "/docs/linguagens",
  label: "🧑‍💻 Linguagens",
  className: 'sidebarLanguagesLink'
}

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [ languagesLink, { type: "autogenerated", dirName: "." } ],
  pythonSidebar: [ languagesLink, ...pythonSidebarItems],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
